### PR TITLE
Use PyLong_AsVoidPtr

### LINKED ISSUE #653: cocotb fails to initialize in 32-bit Aldec since #629
I'm getting [this error message](https://github.com/potentialventures/cocotb/files/2310091/simlog.txt) when running *any* cocotb testbench in the following environment:

 - 32-bit Riviera-PRO 2017.10.67.6735
 - 32-bit Python 3.6.5
 - VHDL/VHPI interface
 - Running on 64-bit CentOS (we're using the 32-bit simulator for licensing reasons)

This happens since [this commit](https://github.com/potentialventures/cocotb/pull/629/commits/56c4ec1428343b63caad02a9b576b4b5cf9b2403) in #629. @eric-wieser, you mentioned that you found more issues related to #629, do you expect that those will eventually fix this problem as well?

### PR DESCRIPTION
**Pull request by jeroenvanstraten**
Fixes #653, see issue for details. @eric-wieser, can you check if this works in your environment as well?

### CODE REVIEW

File: lib/simulator/simulatormodule.c [hunk 1]
```diff
@@ -519,7 +534,7 @@ static PyObject *next(PyObject *self, PyObject *args)
     PyGILState_STATE gstate;
     gstate = TAKE_GIL();
 
-    if (!PyArg_ParseTuple(args, "l", &hdl)) {
+    if (!PyArg_ParseTuple(args, "O&", gpi_sim_hdl_converter, &hdl)) {
```
Comment (eric-wieser) [inline lib/simulator/simulatormodule.c]: `hdl` is a `gpi_iterator_hdl` here, not a `gpi_sim_hdl`. They're typedef'd to the same thing, so you can get away with it - but this name is wrong.

File: lib/simulator/simulatormodule.c [hunk 2]
```diff
@@ -1024,7 +1039,10 @@ static PyObject *deregister_callback(PyObject *self, PyObject *args)
     gstate = TAKE_GIL();
 
     pSihHdl = PyTuple_GetItem(args, 0);
-    hdl = (gpi_sim_hdl)PyLong_AsLong(pSihHdl);
+    if (!gpi_sim_hdl_converter(pSihHdl, &hdl)) {
```
Comment (eric-wieser) [inline lib/simulator/simulatormodule.c]: May as well rewrite this to `if (!PyArg_ParseTuple(args, "O&", gpi_sim_hdl_converter, &hdl)`, which will check the number of arguments too

**Comment by stuarthodgson** [comment]
Looks good, does this fix 32 bit windows? Can anyone check 32 bit sim on 64 bit Linux too?

**Comment by jeroenvanstraten** [comment]
Our environment is a 32-bit simulator on 64-bit Linux, that works again with this fix.

**Comment by cnshijin** [comment]
It also fixes #651 @eric-wieser .
